<img src="skk_gsb1.png"></img>

<center><font size="6">Team Project 1 - Content vs Price Sensitive Customer</font></center>
<p>
<center><font size="3">Business Forecast by Yanbo Wang</font></center>

<center><font size="3">Team 6: Park Keuntae, Nur Afiqah binti Ahmad Shukri</font></center>

# Background

## Business Context

You are working for an **online book platform** that offers both paid and free content. The company’s leadership wants to **differentiate** customers who are **content/experience-driven** (i.e., they buy books and engage deeply with them) from those who are **price-driven** (i.e., they focus on free content, sampling, or finding deals).

**Business Problem**: By identifying whether a customer is content- or price-driven, the marketing team can tailor promotions, upsell strategies, and new feature developments.

1. **Content/experience-driven customers** might respond better to:
   - Exclusive previews or early access to premium books.  
   - Advanced reading features (e.g., curated reading lists, advanced highlighting capabilities).

2. **Price-driven customers** might respond better to:
   - Discount offers or bundle deals.  
   - Extended free trials or “limited-time” free chapters.

---

## Why This Matters

- **Revenue Maximization**: If you misclassify a content-driven customer as price-driven, you might offer unneeded discounts and lose revenue.  
- **Customer Satisfaction**: Price-driven customers pushed with expensive premium items may feel alienated. Conversely, content-driven customers might be willing to pay more for better reading experiences—and you want to serve them accordingly.  
- **Long-term Loyalty**: Matching the right offers to the right user segment helps increase retention (reduce churn) and fosters loyalty.

---

# Dataset

## Data Files

- team_project_1.csv : This file contains data for past customers who used liveBook and whether or not they indicate in a survay that they care content more or price more. For each customer, there is a set of measurements about the use of liveBook by the customers. These measurements are described in more detail below.

## Variables in Data

The measurements of the customers, also known as the “features” of the dataset, are described below:

- Content Driven Customer: 1 if they indicate in a survay that they care content more, 0 if care price more.

- readingownedbook: This is how many events of reading a book the customer-owned.

- ebookdownloaded: This is how many times the customer downloads an e-book.

- readingfreepreview : This is how many times the customer read a free preview.

- highlightcreated: This is how many highlights the customer created.

- freecontentcheckout: This is how many times the customer used the free content check-out feature.

- readingopenchapter: This is how many times the customer read an open (free) chapter.

- wishlistitemadded: This is how many times the customer added items to their wish list.

- crossreferencetermopened: This is how many times the customer opened a cross-reference term.

- total_events: This is the total number of events logged for the customer.

- distinct_products: This is how many distinct products the customer purchased in the previous period.

- reading_utilities: This is how many times the customer used all reading utilities, including highlights and cross-reference terms.

- downloads_per_book: This is how many e-book downloads the customer had divided by the number of books they owned.

- percent_reading: This is the percent of the customers’ events that included reading.

- percent_utilities: This is the percent of the customers’ events that were utility features.

- events_per_book: This is the number of events the customer had divided by the distinct number of books they purchased.


## Data Collection Process

We recruited a select group of existing customers and offered them a modest incentive (e.g., gift cards, account credits) to complete a short survey about their primary motivation when purchasing books on our platform. The survey asked targeted questions such as:

* How important is reading quality, features (like highlighting or cross-referencing), and overall experience in your buying decision?
* How important are discounts, promotions, and overall price when making a purchase?
* Based on their answers, we categorized each respondent as either content/experience-driven or price-driven. This survey-labeled dataset now serves as a valuable “ground truth” for building and validating our predictive models on broader customer data.

# Team Project Tasks



## Task A: Regression Without Interaction Terms

1. **Set Up a Linear Regression**: Use a package like `statsmodels` to create a simple regression model.  
   - **Features**: Use your set of features *excluding* newly engineered interactions.  
   - **Target**: `y` (the dummy variable: 1 if content-driven, 0 if price-driven).  
2. **Fit the Model** and observe:
   - The coefficient estimates.  
   - The significance of each coefficient (if using `statsmodels`).  

**Question**: Which features appear most predictive of a user being content-driven vs. price-driven?

---

## Task B: Regression With Interaction Terms

1. **Enhance the Model**: Now **add** the interaction terms you created in Task B to your feature set.  
2. **Fit a New Model**. Compare:
   - Changes in the R-squared (or other evaluation metrics).  
   - Changes in the significance and magnitude of the main effects when interaction terms are introduced.  
   - Which interactions turned out to be strong predictors?

---

## Task C: Interpretation and Recommendations

1. **Which Features Matter Most?** Summarize the regression results:
   - Positive drivers (can be individual features or interaction of features) of a user being content-driven.  
   - Negative drivers (features that indicate price sensitivity).  
2. **What Are the Practical Implications?** Suppose you’re presenting to the marketing team:
   - How might you **segment customers** or **tailor promotions** based on these findings?  
   - Which features or behaviors would you track more closely going forward?

**Hint**:

**It is possible that one feature might affect the predicted value alone.** For example:

High readingownedbook: These customers spend a lot of time reading books they have already purchased, indicating they deeply value the reading experience.

**It is equally possible that two features jointly affect the predicted value (i.e. interaction effects of features).** For example,

A strong interaction may occur between percent_reading and highlightcreated or crossreferencetermopened. A high proportion of reading events (percent_reading) plus active use of reading utilities is an even stronger indicator of someone who’s driven by the reading experience.

**Deliverable**: A 2-3 page **report** explaining:
- **Key takeaways** from the regression analysis.  
- **Practical suggestions** on how to leverage these insights in marketing, product development, or customer support.

**Good luck**, and we look forward to reviewing your insights on how to identify and serve these two distinct customer segments!

# Predict Customer Churn with OLS Linear Regression

## Task A: Regression Analysis without Interaction Effects

We use the first 20000 rows to fit regression model. We hold back the remaining rows for the subsequent model evaluation purpose.

In [1]:
features = [
    'readingownedbook', 'ebookdownloaded', 'readingfreepreview',
    'highlightcreated', 'freecontentcheckout', 'readingopenchapter',
    'wishlistitemadded', 'crossreferencetermopened', 'total_events',
    'distinct_products', 'reading_utilities', 'downloads_per_book',
    'percent_reading', 'percent_utilities', 'events_per_book'
]

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd

df=pd.read_csv('/content/drive/MyDrive/BF/team_project_1.csv')
df=df.iloc[:20000, :]
df.head()

,account_id,metric_time,readingownedbook,ebookdownloaded,readingfreepreview,highlightcreated,freecontentcheckout,readingopenchapter,wishlistitemadded,crossreferencetermopened,total_events,distinct_products,reading_utilities,downloads_per_book,percent_reading,percent_utilities,events_per_book,Content Driven Customer
0,0001b5d2fd33d5b98539d39658d69a90,2020-03-01,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,2.0,0.0,0.0,0.8125,0.0,8.0,1
1,00036f182bb0746fc8048d8e0bc785b3,2020-03-01,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0000,0.0,1.0,0
2,0006aabe0ba47a35c0b0bf6596f85159,2020-03-01,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0000,0.0,1.0,0
3,0006d94927acb83fdfae843f80d54507,2020-03-01,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,1.0,0.0000,0.0,2.0,1
4,000aa02f54c61c18c94096fc563115f8,2020-03-01,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,0.0,2.0,0.0000,0.0,2.0,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   account_id                20000 non-null  object
 1   metric_time               20000 non-null  object
 2   readingownedbook          20000 non-null  float64
 3   ebookdownloaded           20000 non-null  float64
 4   readingfreepreview        20000 non-null  float64
 5   highlightcreated          20000 non-null  float64
 6   freecontentcheckout       20000 non-null  float64
 7   readingopenchapter        20000 non-null  float64
 8   wishlistitemadded         20000 non-null  float64
 9   crossreferencetermopened  20000 non-null  float64
 10  total_events              20000 non-null  float64
 11  distinct_products         20000 non-null  float64
 12  reading_utilities         20000 non-null  float64
 13  downloads_per_book        20000 non-null  float64
 14  percent_reading           20000 non-null  float64
 15  percent_utilities         20000 non-null  float64
 16  events_per_book           20000 non-null  float64
 17  Content Driven Customer   20000 non-null  int64
dtypes: float64(15), int64(1), object(2)
memory usage: 2.7+ MB

In [7]:
import statsmodels.api as sm
import numpy as np

# Define X and y
X = df[features]
y = df['Content Driven Customer']

# Add a constant to the model(Adding y-intercept)
X = sm.add_constant(X)

# Fit the OLS model
model = sm.OLS(y, X).fit()
print(model.summary())

# Summary table into a DataFrame
summary_df = pd.DataFrame({
    "Variable": model.params.index,
    "Coef": model.params.values,
    "Std Err": model.bse.values,
    "t": model.tvalues,
    "P>|t|": model.pvalues,
    "CI 2.5%": model.conf_int()[0],
    "CI 97.5%": model.conf_int()[1]
})

                               OLS Regression Results
===================================================================================
Dep. Variable:     Content Driven Customer   R-squared:                       0.305
Model:                                 OLS   Adj. R-squared:                  0.305
Method:                      Least Squares   F-statistic:                     627.3
Date:                     Thu, 13 Feb 2025   Prob (F-statistic):               0.00
Time:                             06:26:46   Log-Likelihood:                -10789.
No. Observations:                    20000   AIC:                         2.161e+04
Df Residuals:                        19985   BIC:                         2.173e+04
Df Model:                               14
Covariance Type:                 nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                        0.1326      0.007     19.406      0.000       0.119       0.146
readingownedbook             0.0006      0.000      4.654      0.000       0.000       0.001
ebookdownloaded              0.0010      0.001      1.781      0.075      -0.000       0.002
readingfreepreview           0.0037      0.001      3.501      0.000       0.002       0.006
highlightcreated             0.0026      0.000      6.840      0.000       0.002       0.003
freecontentcheckout         -0.0113      0.002     -6.428      0.000      -0.015      -0.008
readingopenchapter           0.0023      0.001      2.674      0.008       0.001       0.004
wishlistitemadded           -0.0047      0.001     -4.533      0.000      -0.007      -0.003
crossreferencetermopened     0.0049      0.001      7.483      0.000       0.004       0.006
total_events                -0.0008   6.17e-05    -12.665      0.000      -0.001      -0.001
distinct_products            0.0232      0.001     25.690      0.000       0.021       0.025
reading_utilities           -0.0025      0.000     -6.659      0.000      -0.003      -0.002
downloads_per_book           0.0912      0.004     24.383      0.000       0.084       0.099
percent_reading              0.6803      0.011     61.027      0.000       0.658       0.702
percent_utilities            0.5469      0.019     28.901      0.000       0.510       0.584
events_per_book              0.0049      0.000     14.135      0.000       0.004       0.006
==============================================================================
Omnibus:                       38.275   Durbin-Watson:                   2.007
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               37.716
Skew:                          -0.095   Prob(JB):                     6.46e-09
Kurtosis:                       2.904   Cond. No.                     6.73e+15
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.05e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

## Regression Analysis with Interactions Effects

## **Question: Which features appear most predictive of a user being content-driven vs. price-driven?**

Based on the regression output, the key predictors determine if customers are content-driven (1) or price-driven (2). Below are regression output of customers being content-driven.


(1) Content-Sensitive Indicators:

>*Percent_reading* is the most predictive feature for determining whether a user is content-driven or price-driven.
>
>- percent_reading (Coefficient:0.6803, p-value: 0.0000), indicates a strong interest into reading are more likely to be content-driven.
>
>Other significant features that customers are being content-driven include:
>- percent_utilities (Coefficient: 0.5469, p-value: 0.0000), indicating strong association with utility feature usage.
- distinct_products (Coefficient: 0.0232, p-value: 0.0000), showing a positive correlation with purchasing diverse products.

(2) Price-Sensitive Indicators:

>- freecontentcheckout (Coefficient: -0.0113, p-value: 0.000), users who frequently check out free content are less likely to be content-driven, reinforcing price sensitivity.

# Task B : Regression with Interaction Terms

We use the first 20000 rows to fit regression model. We hold back the remaining rows for the subsequent model evaluation purpose.

In [8]:
features = [
    'readingownedbook', 'ebookdownloaded', 'readingfreepreview',
    'highlightcreated', 'freecontentcheckout', 'readingopenchapter',
    'wishlistitemadded', 'crossreferencetermopened', 'total_events',
    'distinct_products', 'reading_utilities', 'downloads_per_book',
    'percent_reading', 'percent_utilities', 'events_per_book'
]

In [10]:
import pandas as pd

df=pd.read_csv('/content/drive/MyDrive/BF/team_project_1.csv')
df=df.iloc[:20000, :]
df.head()

,account_id,metric_time,readingownedbook,ebookdownloaded,readingfreepreview,highlightcreated,freecontentcheckout,readingopenchapter,wishlistitemadded,crossreferencetermopened,total_events,distinct_products,reading_utilities,downloads_per_book,percent_reading,percent_utilities,events_per_book,Content Driven Customer
0,0001b5d2fd33d5b98539d39658d69a90,2020-03-01,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,2.0,0.0,0.0,0.8125,0.0,8.0,1
1,00036f182bb0746fc8048d8e0bc785b3,2020-03-01,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0000,0.0,1.0,0
2,0006aabe0ba47a35c0b0bf6596f85159,2020-03-01,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0000,0.0,1.0,0
3,0006d94927acb83fdfae843f80d54507,2020-03-01,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0,0.0,1.0,0.0000,0.0,2.0,1
4,000aa02f54c61c18c94096fc563115f8,2020-03-01,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,0.0,2.0,0.0000,0.0,2.0,0

In [11]:
import pandas as pd
import itertools
import statsmodels.api as sm
import numpy as np

# Generate all possible pairs of features
feature_pairs = list(itertools.combinations(features, 2))

interaction_features = []
# Create interaction terms for each pair
for feature1, feature2 in feature_pairs:
    interaction_name = f"{feature1} x {feature2}"
    interaction_features.append(interaction_name)
    df[interaction_name] = df[feature1] * df[feature2]

# Display the first few rows of the DataFrame with the new interaction columns
df.head()

<ipython-input-11-1613f792f1c9>:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[interaction_name] = df[feature1] * df[feature2]
<ipython-input-11-1613f792f1c9>:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[interaction_name] = df[feature1] * df[feature2]
<ipython-input-11-1613f792f1c9>:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[interaction_name] = df[feature1] * df[feature2]
<ipython-input-11-1613f792f1c9>:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[interaction_name] = df[feature1] * df[feature2]
<ipython-input-11-1613f792f1c9>:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[interaction_name] = df[feature1] * df[feature2]
<ipython-input-11-1613f792f1c9>:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[interaction_name] = df[feature1] * df[feature2]
<ipython-input-11-1613f792f1c9>:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[interaction_name] = df[feature1] * df[feature2]
<ipython-input-11-1613f792f1c9>:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[interaction_name] = df[feature1] * df[feature2]

,account_id,metric_time,readingownedbook,ebookdownloaded,readingfreepreview,highlightcreated,freecontentcheckout,readingopenchapter,wishlistitemadded,crossreferencetermopened,...,reading_utilities x downloads_per_book,reading_utilities x percent_reading,reading_utilities x percent_utilities,reading_utilities x events_per_book,downloads_per_book x percent_reading,downloads_per_book x percent_utilities,downloads_per_book x events_per_book,percent_reading x percent_utilities,percent_reading x events_per_book,percent_utilities x events_per_book
0,0001b5d2fd33d5b98539d39658d69a90,2020-03-01,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.5,0.0
1,00036f182bb0746fc8048d8e0bc785b3,2020-03-01,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0006aabe0ba47a35c0b0bf6596f85159,2020-03-01,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0006d94927acb83fdfae843f80d54507,2020-03-01,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
4,000aa02f54c61c18c94096fc563115f8,2020-03-01,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0

In [12]:
print(interaction_features)

['readingownedbook x ebookdownloaded', 'readingownedbook x readingfreepreview', 'readingownedbook x highlightcreated', 'readingownedbook x freecontentcheckout', 'readingownedbook x readingopenchapter', 'readingownedbook x wishlistitemadded', 'readingownedbook x crossreferencetermopened', 'readingownedbook x total_events', 'readingownedbook x distinct_products', 'readingownedbook x reading_utilities', 'readingownedbook x downloads_per_book', 'readingownedbook x percent_reading', 'readingownedbook x percent_utilities', 'readingownedbook x events_per_book', 'ebookdownloaded x readingfreepreview', 'ebookdownloaded x highlightcreated', 'ebookdownloaded x freecontentcheckout', 'ebookdownloaded x readingopenchapter', 'ebookdownloaded x wishlistitemadded', 'ebookdownloaded x crossreferencetermopened', 'ebookdownloaded x total_events', 'ebookdownloaded x distinct_products', 'ebookdownloaded x reading_utilities', 'ebookdownloaded x downloads_per_book', 'ebookdownloaded x percent_reading', 'ebookdownloaded x percent_utilities', 'ebookdownloaded x events_per_book', 'readingfreepreview x highlightcreated', 'readingfreepreview x freecontentcheckout', 'readingfreepreview x readingopenchapter', 'readingfreepreview x wishlistitemadded', 'readingfreepreview x crossreferencetermopened', 'readingfreepreview x total_events', 'readingfreepreview x distinct_products', 'readingfreepreview x reading_utilities', 'readingfreepreview x downloads_per_book', 'readingfreepreview x percent_reading', 'readingfreepreview x percent_utilities', 'readingfreepreview x events_per_book', 'highlightcreated x freecontentcheckout', 'highlightcreated x readingopenchapter', 'highlightcreated x wishlistitemadded', 'highlightcreated x crossreferencetermopened', 'highlightcreated x total_events', 'highlightcreated x distinct_products', 'highlightcreated x reading_utilities', 'highlightcreated x downloads_per_book', 'highlightcreated x percent_reading', 'highlightcreated x percent_utilities', 'highlightcreated x events_per_book', 'freecontentcheckout x readingopenchapter', 'freecontentcheckout x wishlistitemadded', 'freecontentcheckout x crossreferencetermopened', 'freecontentcheckout x total_events', 'freecontentcheckout x distinct_products', 'freecontentcheckout x reading_utilities', 'freecontentcheckout x downloads_per_book', 'freecontentcheckout x percent_reading', 'freecontentcheckout x percent_utilities', 'freecontentcheckout x events_per_book', 'readingopenchapter x wishlistitemadded', 'readingopenchapter x crossreferencetermopened', 'readingopenchapter x total_events', 'readingopenchapter x distinct_products', 'readingopenchapter x reading_utilities', 'readingopenchapter x downloads_per_book', 'readingopenchapter x percent_reading', 'readingopenchapter x percent_utilities', 'readingopenchapter x events_per_book', 'wishlistitemadded x crossreferencetermopened', 'wishlistitemadded x total_events', 'wishlistitemadded x distinct_products', 'wishlistitemadded x reading_utilities', 'wishlistitemadded x downloads_per_book', 'wishlistitemadded x percent_reading', 'wishlistitemadded x percent_utilities', 'wishlistitemadded x events_per_book', 'crossreferencetermopened x total_events', 'crossreferencetermopened x distinct_products', 'crossreferencetermopened x reading_utilities', 'crossreferencetermopened x downloads_per_book', 'crossreferencetermopened x percent_reading', 'crossreferencetermopened x percent_utilities', 'crossreferencetermopened x events_per_book', 'total_events x distinct_products', 'total_events x reading_utilities', 'total_events x downloads_per_book', 'total_events x percent_reading', 'total_events x percent_utilities', 'total_events x events_per_book', 'distinct_products x reading_utilities', 'distinct_products x downloads_per_book', 'distinct_products x percent_reading', 'distinct_products x percent_utilities', 'distinct_products x events_per_book', 'reading_utilities x downloads_per_book', 'reading_utilities x percent_reading', 'reading_utilities x percent_utilities', 'reading_utilities x events_per_book', 'downloads_per_book x percent_reading', 'downloads_per_book x percent_utilities', 'downloads_per_book x events_per_book', 'percent_reading x percent_utilities', 'percent_reading x events_per_book', 'percent_utilities x events_per_book']

In [13]:
import statsmodels.api as sm
import numpy as np
import pandas as pd

all_features = features + interaction_features

# Define X and y
X = df[all_features]
y = df['Content Driven Customer']

# Add a constant to the model (Adding y-intercept)
X = sm.add_constant(X)

# Fit the OLS model
model_interaction = sm.OLS(y, X).fit()

print(model_interaction.summary())

# Summary table as a DataFrame

summary_df = pd.DataFrame({
    "Variable": model.params.index,
    "Coef": model.params.values,
    "Std Err": model.bse.values,
    "t": model.tvalues,
    "P>|t|": model.pvalues,
    "CI 2.5%": model.conf_int()[0],
    "CI 97.5%": model.conf_int()[1]
})

summary_df = model_interaction.summary2().tables[1]
print(summary_df)

                               OLS Regression Results
===================================================================================
Dep. Variable:     Content Driven Customer   R-squared:                       0.399
Model:                                 OLS   Adj. R-squared:                  0.395
Method:                      Least Squares   F-statistic:                     118.8
Date:                     Thu, 13 Feb 2025   Prob (F-statistic):               0.00
Time:                             06:27:18   Log-Likelihood:                -9344.2
No. Observations:                    20000   AIC:                         1.891e+04
Df Residuals:                        19888   BIC:                         1.980e+04
Df Model:                              111
Covariance Type:                 nonrobust
==================================================================================================================
                                                     coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------------
const                                              0.0545      0.009      5.992      0.000       0.037       0.072
readingownedbook                                 161.7122    301.821      0.536      0.592    -429.882     753.307
ebookdownloaded                                  181.0975    236.648      0.765      0.444    -282.752     644.947
readingfreepreview                               -26.7652     47.699     -0.561      0.575    -120.259      66.729
highlightcreated                                 -26.7998     47.698     -0.562      0.574    -120.292      66.693
freecontentcheckout                              -26.8030     47.698     -0.562      0.574    -120.295      66.689
readingopenchapter                               -26.7616     47.698     -0.561      0.575    -120.254      66.731
wishlistitemadded                                -26.7541     47.698     -0.561      0.575    -120.247      66.739
crossreferencetermopened                         -26.8067     47.699     -0.562      0.574    -120.300      66.687
total_events                                      96.9772     58.859      1.648      0.099     -18.391     212.346
distinct_products                                  0.0371      0.003     14.423      0.000       0.032       0.042
reading_utilities                               -160.6902    286.190     -0.561      0.574    -721.647     400.267
downloads_per_book                                 0.0633      0.006     10.052      0.000       0.051       0.076
percent_reading                                    0.4200      0.019     22.064      0.000       0.383       0.457
percent_utilities                                  0.3373      0.041      8.147      0.000       0.256       0.418
events_per_book                                    0.0323      0.003     12.380      0.000       0.027       0.037
readingownedbook x ebookdownloaded                 0.0003   3.27e-05      8.968      0.000       0.000       0.000
readingownedbook x readingfreepreview           1.883e-05   5.66e-05      0.332      0.740   -9.22e-05       0.000
readingownedbook x highlightcreated               -0.0001   3.02e-05     -4.862      0.000      -0.000   -8.77e-05
readingownedbook x freecontentcheckout             0.0005      0.000      4.105      0.000       0.000       0.001
readingownedbook x readingopenchapter          -9.832e-05   4.97e-05     -1.980      0.048      -0.000   -9.96e-07
readingownedbook x wishlistitemadded            9.639e-06    8.2e-05      0.118      0.906      -0.000       0.000
readingownedbook x crossreferencetermopened       -0.0002    3.3e-05     -4.608      0.000      -0.000   -8.73e-05
readingownedbook x total_events                 8.194e-06   1.47e-06      5.569      0.000    5.31e-06    1.11e-05
readingownedbook x distinct_products              -0.0004   5.24e-05     -6.998      0.000      -0.000      -0.000
readingownedbook x reading_utilities               0.0002   2.77e-05      6.407      0.000       0.000       0.000
readingownedbook x downloads_per_book             -0.0068      0.001     -6.341      0.000      -0.009      -0.005
readingownedbook x percent_reading                -0.0073      0.002     -4.069      0.000      -0.011      -0.004
readingownedbook x percent_utilities            -487.7077    633.666     -0.770      0.442   -1729.745     754.330
readingownedbook x events_per_book             -6.481e-05   5.53e-06    -11.718      0.000   -7.57e-05    -5.4e-05
ebookdownloaded x readingfreepreview              -0.0008      0.000     -4.515      0.000      -0.001      -0.000
ebookdownloaded x highlightcreated                 0.0003   7.12e-05      4.260      0.000       0.000       0.000
ebookdownloaded x freecontentcheckout             -0.0001      0.000     -0.524      0.601      -0.001       0.000
ebookdownloaded x readingopenchapter               0.0008      0.000      4.864      0.000       0.001       0.001
ebookdownloaded x wishlistitemadded             8.636e-05      0.000      0.546      0.585      -0.000       0.000
ebookdownloaded x crossreferencetermopened        -0.0007      0.000     -3.381      0.001      -0.001      -0.000
ebookdownloaded x total_events                  2.142e-05   9.55e-06      2.242      0.025    2.69e-06    4.01e-05
ebookdownloaded x distinct_products               -0.0002   3.24e-05     -7.627      0.000      -0.000      -0.000
ebookdownloaded x reading_utilities               -0.0004    7.1e-05     -5.555      0.000      -0.001      -0.000
ebookdownloaded x downloads_per_book              -0.0037      0.001     -4.011      0.000      -0.006      -0.002
ebookdownloaded x percent_reading                 -0.0582      0.007     -8.913      0.000      -0.071      -0.045
ebookdownloaded x percent_utilities               -0.0108      0.011     -1.008      0.313      -0.032       0.010
ebookdownloaded x events_per_book                 86.6506     62.079      1.396      0.163     -35.030     208.331
readingfreepreview x highlightcreated          -8.143e-05   7.01e-05     -1.162      0.245      -0.000    5.59e-05
readingfreepreview x freecontentcheckout          -0.0011      0.001     -1.526      0.127      -0.003       0.000
readingfreepreview x readingopenchapter           -0.0003      0.000     -1.782      0.075      -0.001    2.77e-05
readingfreepreview x wishlistitemadded            -0.0013      0.000     -3.147      0.002      -0.002      -0.000
readingfreepreview x crossreferencetermopened     -0.0001      0.000     -0.568      0.570      -0.001       0.000
readingfreepreview x total_events               1.944e-05    5.5e-05      0.353      0.724   -8.84e-05       0.000
readingfreepreview x distinct_products          1.104e-05      0.000      0.050      0.960      -0.000       0.000
readingfreepreview x reading_utilities          9.329e-05   8.57e-05      1.088      0.277   -7.48e-05       0.000
readingfreepreview x downloads_per_book            0.0049      0.003      1.619      0.106      -0.001       0.011
readingfreepreview x percent_reading              69.6614     90.524      0.770      0.442    -107.773     247.096
readingfreepreview x percent_utilities            -0.0294      0.012     -2.495      0.013      -0.052      -0.006
readingfreepreview x events_per_book               0.0002      0.000      0.974      0.330      -0.000       0.001
highlightcreated x freecontentcheckout          5.258e-05      0.000      0.261      0.794      -0.000       0.000
highlightcreated x readingopenchapter           -9.46e-06   3.92e-05     -0.241      0.809   -8.63e-05    6.74e-05
highlightcreated x wishlistitemadded              -0.0010      0.000     -4.349      0.000      -0.001      -0.001
highlightcreated x crossreferencetermopened     2.495e-05   3.53e-05      0.707      0.480   -4.43e-05    9.42e-05
highlightcreated x total_events                 4.001e-06   5.02e-05      0.080      0.936   -9.44e-05       0.000
highlightcreated x distinct_products               0.0002   8.17e-05      2.024      0.043    5.21e-06       0.000
highlightcreated x reading_utilities             2.88e-05   1.13e-05      2.546      0.011    6.63e-06     5.1e-05
highlightcreated x downloads_per_book             -0.0010      0.002     -0.455      0.649      -0.006       0.003
highlightcreated x percent_reading                69.7204     90.524      0.770      0.441    -107.714     247.154
highlightcreated x percent_utilities               0.0071      0.007      1.058      0.290      -0.006       0.020
highlightcreated x events_per_book                 0.0004      0.000      2.336      0.019    6.31e-05       0.001
freecontentcheckout x readingopenchapter          -0.0029      0.001     -4.976      0.000      -0.004      -0.002
freecontentcheckout x wishlistitemadded         9.024e-05      0.000      0.184      0.854      -0.001       0.001
freecontentcheckout x crossreferencetermopened     0.0016      0.000      3.876      0.000       0.001       0.002
freecontentcheckout x total_events                -0.0001   9.59e-05     -1.540      0.123      -0.000    4.02e-05
freecontentcheckout x distinct_products            0.0004      0.000      1.399      0.162      -0.000       0.001
freecontentcheckout x reading_utilities            0.0002      0.000      1.299      0.194      -0.000       0.001
freecontentcheckout x downloads_per_book           0.0167      0.008      2.078      0.038       0.001       0.033
freecontentcheckout x percent_reading             69.6231     90.524      0.769      0.442    -107.811     247.058
freecontentcheckout x percent_utilities            0.0084      0.018      0.473      0.636      -0.027       0.043
freecontentcheckout x events_per_book             -0.0014      0.001     -1.717      0.086      -0.003       0.000
readingopenchapter x wishlistitemadded            -0.0011      0.000     -3.421      0.001      -0.002      -0.000
readingopenchapter x crossreferencetermopened  -8.004e-05      0.000     -0.483      0.629      -0.000       0.000
readingopenchapter x total_events               4.368e-05    5.9e-05      0.740      0.459   -7.21e-05       0.000
readingopenchapter x distinct_products            -0.0004      0.000     -2.054      0.040      -0.001   -1.71e-05
readingopenchapter x reading_utilities          8.912e-06   6.32e-05      0.141      0.888      -0.000       0.000
readingopenchapter x downloads_per_book           -0.0136      0.004     -3.639      0.000      -0.021      -0.006
readingopenchapter x percent_reading              69.6613     90.523      0.770      0.442    -107.772     247.095
readingopenchapter x percent_utilities            -0.0157      0.012     -1.323      0.186      -0.039       0.008
readingopenchapter x events_per_book               0.0003      0.000      1.518      0.129   -8.07e-05       0.001
wishlistitemadded x crossreferencetermopened      -0.0014      0.000     -3.287      0.001      -0.002      -0.001
wishlistitemadded x total_events                   0.0002   7.58e-05      2.766      0.006     6.1e-05       0.000
wishlistitemadded x distinct_products             -0.0011      0.000     -4.709      0.000      -0.002      -0.001
wishlistitemadded x reading_utilities              0.0007      0.000      3.274      0.001       0.000       0.001
wishlistitemadded x downloads_per_book            -0.0072      0.008     -0.924      0.355      -0.023       0.008
wishlistitemadded x percent_reading               69.5896     90.524      0.769      0.442    -107.845     247.024
wishlistitemadded x percent_utilities             -0.0067      0.015     -0.445      0.657      -0.036       0.023
wishlistitemadded x events_per_book               -0.0002      0.001     -0.233      0.815      -0.001       0.001
crossreferencetermopened x total_events         3.275e-05   4.93e-05      0.664      0.506   -6.39e-05       0.000
crossreferencetermopened x distinct_products       0.0008      0.000      4.336      0.000       0.000       0.001
crossreferencetermopened x reading_utilities   -2.271e-05   4.13e-05     -0.551      0.582      -0.000    5.82e-05
crossreferencetermopened x downloads_per_book      0.0013      0.004      0.314      0.754      -0.007       0.009
crossreferencetermopened x percent_reading        69.7148     90.523      0.770      0.441    -107.718     247.148
crossreferencetermopened x percent_utilities       0.0240      0.013      1.915      0.055      -0.001       0.048
crossreferencetermopened x events_per_book         0.0003      0.000      1.800      0.072   -2.66e-05       0.001
total_events x distinct_products               -2.168e-05   3.12e-05     -0.694      0.488   -8.29e-05    3.96e-05
total_events x reading_utilities               -3.376e-05   4.82e-05     -0.701      0.483      -0.000    6.07e-05
total_events x downloads_per_book                -86.6485     62.079     -1.396      0.163    -208.329      35.033
total_events x percent_reading                  -161.6999    301.821     -0.536      0.592    -753.294     429.894
total_events x percent_utilities                 187.5025    333.889      0.562      0.574    -466.948     841.953
total_events x events_per_book                 -2.758e-07   3.31e-07     -0.833      0.405   -9.24e-07    3.73e-07
distinct_products x reading_utilities             -0.0001   7.55e-05     -1.435      0.151      -0.000    3.97e-05
distinct_products x downloads_per_book          -181.0797    236.648     -0.765      0.444    -644.930     282.770
distinct_products x percent_reading                0.0642      0.007      8.896      0.000       0.050       0.078
distinct_products x percent_utilities             -0.0434      0.010     -4.130      0.000      -0.064      -0.023
distinct_products x events_per_book              -96.9823     58.859     -1.648      0.099    -212.351      18.386
reading_utilities x downloads_per_book             0.0009      0.002      0.387      0.699      -0.004       0.006
reading_utilities x percent_reading              417.9705    543.142      0.770      0.442    -646.633    1482.574
reading_utilities x percent_utilities             -0.0123      0.005     -2.634      0.008      -0.021      -0.003
reading_utilities x events_per_book               -0.0004      0.000     -2.321      0.020      -0.001   -6.02e-05
downloads_per_book x percent_reading               0.3288      0.021     15.891      0.000       0.288       0.369
downloads_per_book x percent_utilities             0.1872      0.050      3.729      0.000       0.089       0.286
downloads_per_book x events_per_book              -0.0012      0.000     -2.556      0.011      -0.002      -0.000
percent_reading x percent_utilities                1.4523      0.122     11.924      0.000       1.214       1.691
percent_reading x events_per_book                 -0.0153      0.003     -4.939      0.000      -0.021      -0.009
percent_utilities x events_per_book               -0.0324      0.003     -9.655      0.000      -0.039      -0.026
==============================================================================
Omnibus:                      479.532   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              399.189
Skew:                           0.277   Prob(JB):                     2.08e-87
Kurtosis:                       2.585   Cond. No.                     1.51e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.11e-17. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
                                             Coef.    Std.Err.          t  \
const                                     0.054506    0.009097   5.991920
readingownedbook                        161.712197  301.821130   0.535788
ebookdownloaded                         181.097502  236.648037   0.765261
readingfreepreview                      -26.765150   47.698918  -0.561127
highlightcreated                        -26.799756   47.698211  -0.561861
...                                            ...         ...        ...
downloads_per_book x percent_utilities    0.187184    0.050193   3.729304
downloads_per_book x events_per_book     -0.001152    0.000451  -2.555663
percent_reading x percent_utilities       1.452262    0.121794  11.923909
percent_reading x events_per_book        -0.015258    0.003089  -4.938835
percent_utilities x events_per_book      -0.032380    0.003354  -9.654827

                                               P>|t|      [0.025      0.975]
const                                   2.109488e-09    0.036676    0.072336
readingownedbook                        5.921109e-01 -429.882351  753.306745
ebookdownloaded                         4.441253e-01 -282.752356  644.947360
readingfreepreview                      5.747173e-01 -120.259002   66.728702
highlightcreated                        5.742172e-01 -120.292221   66.692710
...                                              ...         ...         ...
downloads_per_book x percent_utilities  1.925421e-04    0.088802    0.285565
downloads_per_book x events_per_book    1.060595e-02   -0.002036   -0.000269
percent_reading x percent_utilities     1.148121e-32    1.213535    1.690988
percent_reading x events_per_book       7.922796e-07   -0.021314   -0.009203
percent_utilities x events_per_book     5.241129e-22   -0.038953   -0.025806

[121 rows x 6 columns]

# Task B: Questions and answers

**Changes in the R-squared (or other evaluation metrics).**

- Model without interaction variable : 0.305
- Model with interaction variable : 0.399

**Changes in the significance and magnitude of the main effects when interaction terms are introduced.**

 **1. Percent_reading** (the most predictive features in the original model)

Original Model:
- Coefficient: 0.6803
- P-value: 0.0000

Interaction Model:
- Coefficient: 0.4200
- P-value: 0.0000

Summary: Although the magnitude of percent_reading’s main effect decreases, it remains a strong and significant predictor, suggesting that its impact partly depends on the context provided by other variables.

**2. Percent_utilities**

Original Model:
- Coefficient: 0.5469
- P-value: 0.0000

Interaction Model:
- Coefficient: 0.3373
- P-value: 0.0000

Summary: The decrease in the coefficient implies that the role of percent_utilities is partly moderated by other features in the model.

**3. Distinct_products**

Original Model:
- Coefficient: 0.0232
- P-value: 0.0000

Interaction Model:
- Coefficient: 0.0371
- P-value: 0.0000

Summary: With interaction terms, the coefficient for distinct_products rises to 0.0371, indicating a stronger influence, likely due to its amplified effect when combined with other behavioral metrics.

> **Other remaining changes in the significance and magnitude of the main effects features:**

4) downloads_per_book:

Original Model:
- Coefficient: 0.0912
- P-value: 0.0000

Interaction:
- Coefficient 0.0633
- P-value: 0.0000

Summary: With interaction terms, the coefficient for downloads_per_book  decreases to 0.0633 is partly affected by other metrics in the model.


5) events_per_book:

Original Model:
- Coefficient: 0.0049
- P-value: 0.0000

Interaction:
- Coefficient: 0.0323
- P-value: 0.0000

Summary: The decrease in the coefficient implies that the role of events_per_book is partly impacted by other features in the model.


# **Q2. Which interactions turned out to be strong predictors?**

# A. Strong interaction predictors (p < 0.001 with high t-values) include:
- readingownedbook × ebookdownloaded: Coefficient = 0.0003, t ≈ 8.97
- readingownedbook × events_per_book: Coefficient = –6.481e-05, t ≈ –11.72
- ebookdownloaded × percent_reading: Coefficient = –0.0582, t ≈ –8.91
- downloads_per_book × percent_reading: Coefficient = 0.3288, t ≈ 15.89
- percent_reading × percent_utilities: Coefficient = 1.4523, t ≈ 11.92


These interactions indicate that the effect of one predictor significantly depends on another, enhancing the overall model’s explanatory power.

- readingownedbook × ebookdownloaded: Users who own physical books are also interested in eBooks. Rather than fully replacing them, they increased the engagement through digitalisation.

- readingownedbook × events_per_book: This shows an inverse relationship. Owning more books decreases the interest to engage in event because customers already have their preference on their own collection.

- ebookdownloaded × percent_reading: The negative coefficient indicates that ebooks tend to affect the reading percentage negatively. It does not result in increased reading activity.

- downloads_per_book × percent_reading: The strong positive relationship indicates that as number of download per book increases, the percent reading also increases. It indicates a high engagement in reading behavior among users.  

- percent_reading × percent_utilities: This shows that customers who spend more time on reading, use the reading utilities effictively. The high coefficient suggests that reading engagement relates with the digital tool usage and making this as the strongest key predictor in this model.

# Task C: Interpretation and Recommendations

# Q1. **Which Features Matter Most? Summarize the regression results**
- Positive drivers (can be individual features or interaction of features) of a user being content-driven.
> - "Percent_reading" : +0.4200 (t = 22.06, p < 0.001)
> - "Distinct_products" : +0.0371 (t = 14.42, p < 0.001)
> - "Downloads_per_book" : +0.0633 (t = 10.05, p < 0.001)


- Negative drivers (features that indicate price sensitivity).
> - "Reading Owned Books × Downloads per Book" : –0.0068 (t = –6.34, p < 0.001)
> - "Reading Owned Books × Events per Book" : –6.48e-05 (t = –11.72, p < 0.001)
> - "eBook Downloaded × Percent Reading" : –0.0582 (t = –8.91, p < 0.001)

The model sorts customers into two groups: content-driven (1) or price-driven (0), based on their survey answers. If a customer is highly engaged with content, they get a 1, meaning those with lower engagement are seen as price-driven.

However, the negative drivers in the model simply show less content engagement—they do not directly prove price sensitivity. So, assuming that "not content-driven" automatically means "price-driven" is just a way to simplify things, but real customer behavior may be more complicated.

# Q2. **What Are the Practical Implications? Suppose you’re presenting to the marketing team**
>- How might you **segment customers** or **tailor promotions** based on these findings?  

Based on the findings and regression outcome, customers can be segmented into content-driven and prive-driven readers. Both groups of readers can be approached with a well-planned marketing strategies.

Content-driven readers:
- Segment: Engaged readers
- Features: High percent_reading, high distinct_products, high downloads_per_book
- Marketing Strategy: To offer exclusive early access with exclusive contents to attract loyalty and eagerness to be a part of the reading community based one each preferences.

Price-driven readers:
- Segment: Readers who seek for bargains
- Features: Low percent_reading, low events_per_book, high reading_books
- Marketing Strategy: To provide discounts and promotions within limited-time with exclusive highlights or contents.


>- Which features or behaviors would you track more closely going forward?
As for marketing strategies, our team would:

1. Track and analyse the engagement metrics
- As proven from the regression output above, we would monitor the percent_reading with percent_utilties. Example, if users percent_reading is high and they use utilities such as annotations, highlights or bookmarks, it defines their reading behavior after promotional events.

2. To understand customers' download behavior
- Analysing the engagement metrics, we would identify their group categories to content-driven readers or price-driven readers. For example, to analyse whether customers fully utilise the percent_reading based on the downloads_per_book.

For more detailed explanations based on tasks and questions given, it is answered on the report attached in the assignment submission.